server:
  port: 6059

spring:
  profiles:
    active: @profileActive@

app:
  name: user

logging:
  file:
    path: ./logs
    name: business
  level:
    # mapper包下打印debug级别日志
    com.yxx.business.mapper: debug
