spring:
  application:
    name: business
  config:
    activate:
      on-profile: prod
  # mysql 通用配置信息内容 使用HikariDataSource连接池
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://198.44.169.16:3306/base_springboot?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: Mysql@{110}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  # 请求大小
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  data:
    # redis 配置内容
    redis:
      # 设置初始数据库的数据为8
      database: 8
      host: 198.44.169.16
      port: 7288
      password: Redis@{110}
      jedis:
        pool:
          # 连接池最大连接数（使用负值表示没有限制）
          max-active: 50
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: 3000ms
          # 连接池中的最大空闲连接数
          max-idle: 20
          # 连接池中的最小空闲连接数
          min-idle: 5
      # 连接超时时间（毫秒）
      timeout: 5000ms
  # 邮箱
  mail:
    # 编码
    default-encoding: UTF-8
    # 邮件服务器
    host: smtp.email.cn
    # 用户名(一般为邮箱号)
    username: shuniversity@email.cn
    # 邮件服务器端口
    port: 25
    # 专用密码
    password: 2BCZKEGQgHyCZ5i4

# 邮箱设置
mail:
  # 发件人邮箱
  from: shuniversity@email.cn
  # 发件人名称
  from-name: SpringBoot开发模版
  # 注册时邮箱验证码有效期
  register-time: 5
  # 一个邮箱每日最大注册次数 (防止恶意发送邮件)
  register-max: 3
  # 注册邮件正文
  register-content: >
    <!DOCTYPE html>
    <html>
    <head>
      <title>注册验证码邮件</title>
      <style>
        /* 基本样式 */
        body {
          font-family: Arial, sans-serif;
          line-height: 1.6;
          color: #333;
        }
        .container {
          max-width: 600px;
          margin: 0 auto;
          padding: 20px;
        }
        h1 {
          color: #695d9d;
        }
        p {
          margin-bottom: 20px;
        }
        .verification-code {
          background-color: #695d9d;
          color: #fff;
          font-size: 20px;
          font-weight: bold;
          padding: 5px 10px;
          border-radius: 5px;
          margin: 10px 0;
          display: inline-block;
        }
        .footer {
          text-align: center;
        }
        .footer p {
          color: #777;
        }
      </style>
    </head>
    <body>
      <div class="container">
        <h1>欢迎注册！</h1>
        <p>感谢您注册我们的服务。以下是您的验证码：</p>
        <span class="verification-code"> {captcha} </span>
        <p>此验证码将在 {time} 分钟后失效，请及时使用。</p>
        <p>如果您没有进行注册操作，请忽略此邮件。</p>
        <div class="footer">
          <p>此邮件由 <a style="color:#695d9d;text-decoration: none;" href="{domain}">{formName}</a> 发送</p>
          <p>如有疑问，请联系我们：{form}</p>
        </div>
      </div>
    </body>
    </html>

  # ip异常邮件正文
  ip-unusual-content: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>IP异常提醒</title>
      <style>
        body {
          font-family: Arial, sans-serif;
          line-height: 1.6;
          color: #333;
        }
        .container {
          max-width: 600px;
          margin: 0 auto;
          padding: 20px;
          border: 1px solid #ddd;
          border-radius: 5px;
        }
        h1 {
          color: #695d9d;
        }
        table {
          width: 100%;
          border-collapse: collapse;
          margin-bottom: 20px;
        }
        th, td {
          padding: 10px;
          text-align: left;
          border-bottom: 1px solid #ddd;
        }
        th {
          background-color: #f5f5f5;
        }
        .footer {
          text-align: center;
        }
        .footer p {
          color: #777;
        }
      </style>
    </head>
    <body>
      <div class="container">
        <h1>IP异常提醒</h1>
        <p>您的账户在以下时间出现异常登录：</p>
        <table>
          <tr>
            <th>登录时间</th>
            <th>登录IP</th>
            <th>登录地址</th>
            <th>登录设备</th>
          </tr>
          <tr>
            <td>{time}</td>
            <td>{ip}</td>
            <td>{address}</td>
            <td>{agent}</td>
          </tr>
        </table>
        <p>如果这些登录不是您的操作，请尽快修改密码并确保账户安全。</p>
        <div class="footer">
          <p>此邮件由 <a style="color:#695d9d;text-decoration: none;" href="{domain}">{formName}</a> 发送</p>
          <p>如有疑问，请联系我们：{form}</p>
        </div>
      </div>
    </body>
    </html>


# 重置密码
reset-password:
  # 找回密码页面url
  base-path: http://127.0.0.1
  # 每日找回密码最大次数 (防止恶意发送邮件)
  max-number: 3
  # 找回密码邮件正文
  reset-pwd-content: >
    <!DOCTYPE html>
    <html>
    <head>
      <title>重置密码</title>
      <style>
        body {
          font-family: Arial, sans-serif;
          line-height: 1.6;
          color: #333;
        }
        .container {
          max-width: 600px;
          margin: 0 auto;
          padding: 20px;
          border: 1px solid #ddd;
          border-radius: 5px;
        }
        h1 {
          color: #695d9d;
        }
        .instructions {
          margin-top: 20px;
        }
        .button {
          display: inline-block;
          margin-top: 20px;
          padding: 10px 20px;
          background-color: #695d9d;
          color: #fff;
          text-decoration: none;
          border-radius: 5px;
        }
        .footer {
          text-align: center;
          margin-top: 20px;
          color: #777;
        }
      </style>
    </head>
    <body>
      <div class="container">
        <h1>重置密码</h1>
        <p>亲爱的用户，您收到这封邮件是因为您请求重置密码。</p>
        <p class="instructions">请点击下面的按钮来设置一个新密码：</p>
        <a class="button" href="{url}">重置密码</a>
        <p class="instructions">请注意，此链接将在接下来的{time}分钟内有效，请尽快完成密码重置操作。</p>
        <p class="instructions">如果您没有请求重置密码，请忽略此邮件。</p>
        <div class="footer">
          <p>此邮件由 <a style="color:#695d9d;text-decoration: none;" href="{domain}">{formName}</a> 发送</p>
          <p>如有疑问，请联系我们：{form}</p>
        </div>
      </div>
    </body>
    </html>

  # 重置密码链接有效期（单位：分钟）
  reset-pwd-time: 15

# 是否校验ip异常
ip:
  # 开启后则校验ip异常情况 (异地换设备登录) 发送邮件通知
  check: false

# 网站域名
web:
  domain: http://127.0.0.1

# mybatis-plus开发日志打印内容
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    db-config:
      logic-delete-field: is_delete
      logic-delete-value: 1
      logic-not-delete-value: 0
    banner: false

# Sa-Token配置
sa-token:
  # token名称 (同时也是cookie名称,可自行更改)
  token-name: Authorization
  # token前缀
  token-prefix: Bearer
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # 是否打开自动续签 (如果此值为true, 框架会在每次直接或间接调用 getLoginId() 时进行一次过期检查与续签操作)
  autoRenew: true
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  active-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false
  # jwt秘钥 请更改为自己的，随意乱按几个字母数字就行
  jwt-secret-key: TUx8IaslTsibligsqvzLmNvbQECAwQF
  # 是否在初始化配置时打印版本字符画
  is-print: false
  # 登录逻辑缓存和业务逻辑缓存分离
  alone-redis:
    # Redis数据库索引（默认为0）
    database: 2
    # Redis服务器地址
    host: 198.44.169.16
    # Redis服务器连接端口
    port: 7288
    # Redis服务器连接密码（默认为空）
    password: Redis@{110}
    # 连接超时时间
    timeout: 10s

# forest配置
forest:
  max-connections: 1000        # 连接池最大连接数
  connect-timeout: 3000        # 连接超时时间，单位为毫秒
  read-timeout: 3000           # 数据读取超时时间，单位为毫秒

# 支付宝配置
ali:
  # 小程序appId
  app_id: 9021000127674048
  #商户公钥
  merchant_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAo2XnNH1Ym2mANXrJVhozeiCgya8G6za0fOWeHTQJvs9itpm3M8TRbkBJUC45GHNOo2TuMPOpU29PFC9/lIGiNCARfMaA53KUYtuydlyZLQXxyyB/mX/C192rqauK7Ql+lmjmIDwQsqTxXi5Cmw9jasm0JUkCP5qNbZvy78taZgYyb7uPYc1VpAC3wR36JQJPaScg0A0Ia/nnx+CLHKPQgB4AoFML1F4kx4yBaGqEuAk++0xxFKW0rLxxfjprmFGg5yAXr/zhKpeua7NCmF/+Nvit/S0/KZog3rbe88A9iwuTAg0h9iyb7tWH/+2rcp9KPYQ4ibOhor5U+kw2kHbuYQIDAQAB
  # 商户私钥
  merchant_private_key: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCjZec0fVibaYA1eslWGjN6IKDJrwbrNrR85Z4dNAm+z2K2mbczxNFuQElQLjkYc06jZO4w86lTb08UL3+UgaI0IBF8xoDncpRi27J2XJktBfHLIH+Zf8LX3aupq4rtCX6WaOYgPBCypPFeLkKbD2NqybQlSQI/mo1tm/Lvy1pmBjJvu49hzVWkALfBHfolAk9pJyDQDQhr+efH4Isco9CAHgCgUwvUXiTHjIFoaoS4CT77THEUpbSsvHF+OmuYUaDnIBev/OEql65rs0KYX/42+K39LT8pmiDett7zwD2LC5MCDSH2LJvu1Yf/7atyn0o9hDiJs6GivlT6TDaQdu5hAgMBAAECggEBAKNX3ICpiambFvLfc2QivzEoavQTh3wd7OIqfRy+h7t7ADiAhBc5ew+XLnL8MlGR+5v16vN+sdfZnxkTvptL2EX5hOHSYsx8y3/kFoyiVvIeTi/8pfJiOPqo+9Gazj/VzPk5lkvFIAAmSbAX2Le/82euier4CEpjC1z2mC5FgHIZyGxRwRSinKMOc0KkigxWnjfUmugTAKgjF40oiaRRFR0JrFo9tfGI682ZCajYSsubnAldlv2rj5/OnutWgJt314TtDD11uOehvq3lVkV0KAyRrfeXj/5SRxG1bFJnUcxmsUdQsu+89xQTlgXebIaEFnqwhp0D/yH7arnzYqa+QEECgYEA1sOfjubFPOv8O5u0Hr3octIrmxqD2lCU5Mp2+7WS4IDbXGH1iciEpR5Vzf2YHyCxnAcDz6blphuQ3dCmPBuwI09/5R7TyIhAHqpUq8FW0NC9jEwqYrSaXzFLvHnxD4fPVIzQW1s86EVDvE0gfyh7o4LhcFRqsBlFQ/Q1sCYmy0kCgYEAwsV254mYmUzlnEv1OCTUwl1h+WBYSF1orZooVEBcCbpAMacNCEKdIF7gwxw5/3MQQXRPgaLh3Qu9YumesGc8SU2RjjMrbHXdQ2l3XLR56iT9DRAMIKG1JyrB7JCPZ5Q8pc+1ODvR/2i90DW3dx1WXOTNPGNGGyfog3UbhTkWMlkCgYBrqYnVg46hKdQ6taWoO5/J396IVNSAnyDlSTI4oR/OeAp/14PV3LXSaNCvAVA/Wo5vH30jnhFGIk+PQ0fynhbAvNvqqneU8eji9pSXvcady+cZ7Bzbeppg2j+TbrYQCQ9A3Y6eHbD856w7O5bs6AiDQdtuCoOpYCG/HS/E7HtKMQKBgQDBohKeCXs+HObAxfsaP/OM782xYIkkGEkzHekuKXXW7eVX953LMn6HagvFrVAzl673g6xvUwF9Amjb5youcdPLhGRKnLB0+ZBprnZOIdZ6Yx94VxXXcyxnrehxSR5oeUT6C088gqw5YWYjkuO8ddwgKg+oE4HlCX3tAwXDIofgsQKBgQCvV1Je/AgROj9iNFViDboNXf/dOnriVUhjq5czTnVgERjDIAq5RqnQ4eRh5G5TrQAisFhv7I0ex1k9tvOdzAYlnio/DZ8Wu5ET1iPNw3G4FMMEFfsG8pqkX7ndkpKrXuAvibTO6JskGQSQlEJ8TG7yqbBCH8ZlqnHJhy/MR0n/cA==
  # 编码格式
  charset: UTF-8
  # 支付宝公钥
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmpo3T8FfKxQiTlyAFVoJC6Adr3LAjf7lLcOrTlOTv5cc0vxBfkD8fLB019upBhMycNVg0U8sMZs+XKFGLpgwWLk7SqX34V75X0YrBnfvzjIgpTnxDSJO+GS0jew0z6OJAQPfIx8nvsrS9KVurIDQLvHrohcO3j2RNzlhT/eGj/A0GLteJyYgjZh/IRoyAOPrQsfSl0oAwxVd/I1z3cXD3swYSgCBGmgUDdxYWLV8wLrVu3zXhhVPnbrmHqcGlxnSwdH142Olkrvo24TtV6qverznJghbnFu9VfjcnLcDbp2nxXRUdE6vWdWpH5JJZehCDujVpjsemLhSaKYNLUEbiQIDAQAB
  # 加密类型
  sign_type: RSA2
  # 支付宝网关
  server_url: https://openapi-sandbox.dl.alipaydev.com/gateway.do
  # 异步回调接口路径
  notify_url: http://198.44.169.16:6059/aliPay/notifyUrl
  # 返回格式
  format: json

